spring.application.name=naval

naval.url=https://cnf.esport.com.pt/Portal/User#checkin
naval.username=${NAVAL_USERNAME}
naval.password=${NAVAL_PASSWORD}

naval.activities[0].type=TENNIS
naval.activities[0].name=T. FUNCIONAL
naval.activities[0].preferredDate=2026-05-20
