spring.application.name=naval

naval.username=${NAVAL_USERNAME}
naval.password=${NAVAL_PASSWORD}

# Example activity configuration:
# naval.activities[0].type=TENNIS
# naval.activities[0].name=Morning Tennis
# naval.activities[0].preferredDate=2024-05-18
